version: '3.1'
services:
  web:
    image: odoo:14.0
    env_file: .env 
    depends_on:
      - db
    ports:
      - "0.0.0.0:8067:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
